### ISSUE TITLE
Update event management

### ISSUE THREAD

**Issue by fzuefo** [AmozPay/OtterLib#88]
Today, the events are stored in a map (with the id of the key and the state) into the encapsulation of the graphic lib.

Many changes are needed:

- Store the map in the game instead of the graphic lib (the code of the key needs to be unknown for the game, as only the graphic lib needs to understand this code)

- Add a new type of key (ONE_TIME or PRESSED), this type will determine if the event handler needs to check for a one time pressed key or a pressing key. This type is useful for the shot for example (in order to avoid long pressed key and so multiple shots)

- Rename the event component from `Keyboard` to `Event`

**Comment by fzuefo** [comment]
good part, this is a important task,
 the graphic need to be abstract 

i advise you to create one or 2 interface to unified the graphic game interaction

**Comment by barbo69** [comment]
No needs to add the input type of the key we can handle it with systems
